<?php

declare(strict_types=1);

namespace App\Presenters;

use Nette;
use Tracy\Debugger;


class BasePresenter extends Nette\Application\UI\Presenter
{

	/** @var string @persistent */
	public $locale = 'sk';

	/** @var \Kdyby\Translation\Translator @inject */
	public $translator;


	public function handleSetLocale($l)
	{
		$this->translator->setLocale($l);
	}


	public function beforeRender()
	{
		parent::beforeRender(); // TODO: Change the autogenerated stub
		$this->template->locales = [];
		foreach ($this->translator->getAvailableLocales() as $l)
		{
			$this->template->locales[] = strtolower(explode('_', $l)[0]);
		}
	}


	public function flashSuccess($msg)
	{
		$this->flashMessage($msg, 'success');
	}

	public function flashDanger($msg)
	{
		$this->flashMessage($msg, 'error');
	}
}
